INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '김치찌개', 5000, 250, '아주 맛있는 김치찌개!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '김치찌개.PNG', '김치찌개.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '감자탕', 10000, 350, '아주 맛있는 감자탕!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '감자탕.PNG', '감자탕.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '된장찌개', 6000, 250, '아주 맛있는 된장찌개!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '된장찌개.PNG', '된장찌개.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '보쌈', 15000, 150, '아주 맛있는 보쌈!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '보쌈.PNG', '보쌈.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '부대찌개', 7000, 150, '아주 맛있는 부대찌개!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '부대찌개.PNG', '부대찌개.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '불고기', 11000, 250, '아주 맛있는 불고기!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '불고기.PNG', '불고기.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '비빔밥', 5000, 350, '아주 맛있는 비빔밥!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '비빔밥.PNG', '비빔밥.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '삼겹살', 9000, 150, '아주 맛있는 삼겹살!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '삼겹살.PNG', '삼겹살.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '순대국', 6000, 350, '아주 맛있는 순대국!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '순대국.PNG', '순대국.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '칼국수', 5000, 250, '아주 맛있는 칼국수!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '칼국수.PNG', '칼국수.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(1, '해물탕', 25000, 150, '아주 맛있는 해물탕!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '해물탕.PNG', '해물탕.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '깐쇼새우', 13000, 130, '정말 맛있는 깐쇼새우!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '깐쇼새우.PNG', '깐쇼새우.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '깐풍기', 15000, 150, '정말 맛있는 깐풍기!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '깐풍기.PNG', '깐풍기.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '마라탕', 5000, 50, '정말 맛있는 마라탕!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '마라탕.PNG', '마라탕.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '마파두부', 9000, 100, '정말 맛있는 마파두부!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '마파두부.PNG', '마파두부.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '볶음밥', 5000, 450, '정말 맛있는 볶음밥!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '볶음밥.PNG', '볶음밥.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '양장피', 16000, 350, '정말 맛있는 양장피!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '양장피.PNG', '양장피.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '유린기', 14000, 50, '정말 맛있는 유린기!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '유린기.PNG', '유린기.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '짜장면', 5000, 450, '정말 맛있는 짜장면!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '짜장면.PNG', '짜장면.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '짬뽕', 7000, 150, '정말 맛있는 짬뽕!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '짬뽕.PNG', '짬뽕.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '크림짬뽕', 8000, 250, '정말 맛있는 크림짬뽕!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '크림짬뽕.PNG', '크림짬뽕.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(2, '탕수육', 14000, 450, '정말 맛있는 탕수육!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '탕수육.PNG', '탕수육.PNG');


INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '규동', 7000, 170, '진짜 맛있는 규동!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '규동.PNG', '규동.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '라멘', 6000, 220, '진짜 맛있는 라멘!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '라멘.PNG', '라멘.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '모츠나베', 15000, 2000, '진짜 맛있는 모츠나베!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '모츠나베.PNG', '모츠나베.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '문어숙회', 16000, 160, '진짜 맛있는 문어숙회!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '문어숙회.PNG', '문어숙회.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '스키야키', 15000, 150, '진짜 맛있는 스키야키!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '스키야키.PNG', '스키야키.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '야끼토리', 12000, 120, '진짜 맛있는 야끼토리!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '야끼토리.PNG', '야끼토리.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '오니기리', 3000, 250, '진짜 맛있는 오니기리!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '오니기리.PNG', '오니기리.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '오코노미야키', 8000, 180, '진짜 맛있는 오코노미야키!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '오코노미야키.PNG', '오코노미야키.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '우동', 4000, 450, '진짜 맛있는 우동!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '우동.PNG', '우동.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '초밥', 12000, 120, '진짜 맛있는 초밥!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '초밥.PNG', '초밥.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(3, '텐동', 6000, 250, '진짜 맛있는 텐동!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '텐동.PNG', '텐동.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '까르보나라', 6000, 150, '핵 맛있는 까르보나라!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '까르보나라.PNG', '까르보나라.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '돈까스', 8000, 750, '핵 맛있는 돈까스!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '돈까스.PNG', '돈까스.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '라구파스타', 5000, 250, '핵 맛있는 라구파스타!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '라구파스타.PNG', '라구파스타.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '로제', 7000, 350, '핵 맛있는 로제!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '로제.jpg', '로제.jpg');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '마르게리타피자', 6000, 230, '핵 맛있는 마르게리타피자!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '마르게리타피자.PNG', '마르게리타피자.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '반반피자', 16000, 140, '핵 맛있는 반반피자!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '반반피자.PNG', '반반피자.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '봉골레', 7000, 250, '핵 맛있는 봉골레!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '봉골레.jpg', '봉골레.jpg');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '비프샐러드', 7000, 100, '핵 맛있는 비프샐러드!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '비프샐러드.PNG', '비프샐러드.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '새우크림리조또', 14000, 140, '핵 맛있는 새우크림리조또!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '새우크림리조또.PNG', '새우크림리조또.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '스테이크', 16000, 700, '핵 맛있는 스테이크!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '스테이크.PNG', '스테이크.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '치킨', 8000, 2022, '핵 맛있는 치킨!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '치킨.PNG', '치킨.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(4, '햄버거', 4000, 450, '핵 맛있는 햄버거!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '햄버거.PNG', '햄버거.PNG');


INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(5, '땡초불고기돈까스새우김밥', 4000, 450, '눈물나게 맛있는 땡초불고기돈까스새우김밥!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '땡초불고기돈까스새우김밥.PNG', '땡초불고기돈까스새우김밥.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(5, '떡볶이', 5000, 550, '눈물나게 맛있는 떡볶이!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '떡볶이.PNG', '떡볶이.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(5, '순대', 3000, 350, '눈물나게 맛있는 순대!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '순대.PNG', '순대.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(5, '쫄면', 4000, 450, '눈물나게 맛있는 쫄면!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '쫄면.PNG', '쫄면.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(5, '모둠튀김', 5000, 550, '눈물나게 맛있는 모둠튀김!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '모둠튀김.PNG', '모둠튀김.PNG');


INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '똠양꿍', 12000, 200, '너무 맛있는 똠양꿍!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '똠양꿍.PNG', '똠양꿍.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '분짜', 6000, 600, '너무 맛있는 분짜!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '분짜.PNG', '분짜.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '불고기반미', 4000, 150, '너무 맛있는 불고기반미!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '불고기반미.PNG', '불고기반미.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '새우나시고랭', 9000, 550, '너무 맛있는 새우나시고랭!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '새우나시고랭.PNG', '새우나시고랭.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '쌀국수', 7000, 150, '너무 맛있는 쌀국수!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '쌀국수.PNG', '쌀국수.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '팟타이', 6000, 650, '너무 맛있는 팟타이!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '팟타이.PNG', '팟타이.PNG');

INSERT INTO PRODUCT(CATEGORY_CODE, NAME, PRICE, STOCK, CONTENT, REGISTRATION_DATE)
VALUES(6, '푸팟퐁커리', 10000, 100, '너무 맛있는 푸팟퐁커리!', SYSDATE);
INSERT INTO PRODUCT_IMAGE(PRODUCT_NO, ORIGINAL_NAME, STORED_NAME)
VALUES(SEQ_PRODUCT_NO.currval, '푸팟퐁커리.PNG', '푸팟퐁커리.PNG');

COMMIT;

SELECT *
FROM PRODUCT;
