DELETE ORDER_DETAIL;
DELETE MEMBER_ORDER;

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);


INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);


INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE,
, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-6, 40000, '1' , '2'
, '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);


INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);


INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-5, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);


INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-4, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-3, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-2, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-2, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-2, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-2, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-2, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-2, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);


INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

INSERT INTO MEMBER_ORDER(MEMBER_ID, ORDER_DATE, RECEIVER_NAME, RECEIVER_PHONE
, POST, ADDRESS, ADDRESS_DETAIL, REQUEST, STATE_CODE)
VALUES('dong', SYSDATE-1, '1' , '2', '3', '4', '5', '6', 2);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 4, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 3, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);
INSERT INTO ORDER_DETAIL(ORDER_NO, PRODUCT_NO, QUANTITY, PRICE)
VALUES(SEQ_MEMBER_ORDER_NO.CURRVAL, TRUNC(DBMS_RANDOM.VALUE(1, 58)), 2, TRUNC(DBMS_RANDOM.VALUE(6, 15)) * 1000);

COMMIT;

